// constant strings
String nextText = "Next",
    appName = "RAPSAPP",
    gettingStarted = "Get Started!",
    enterYourName = 'Enter your name',
    enterYourEmail = 'Enter your email',
    enterYouPhoneNumber = 'Enter your phone number',
    enterYourPassword = 'Enter your password',
    signUp = 'Signup',
    login = 'Login',
    sendCode = "Send Code",
    forgetPassword = 'Forgot Password ?',
    orLoginWith = 'Or Login with',
    forgetPassDesc =
        'Don\'t worry! It occurs. Please enter the email address linked with your account.',
    forgetPasswordHead = "Forget Password",
    alreadyHaveAnAccount = 'Already have an account?',
    orSignUpWith = "Or Signup with",
    createAnAccToGetStarted = 'Create an account to get started !',
    welcomeBackMessage = 'Welcome back! Glad to see you, Again!',
    dontHaveAnAcc = 'Don\'t have an account?',
    regNow = 'Register Now',
    emailVerification = 'OTP Verification',
    emailVerificationDesc =
        'Enter the verification code we just sent on your email address.',
    didntRecivedCode = 'Didn\'t received code?',
    verify = 'Verify',
    resend = 'Resend',
    calling = 'Calling ...',
    providersName = 'Provider\'s Name',
    accountCreatedSuccessfullyText = 'Account Created Successfully';

// image location in form of string
String phoneLogo = 'assets/logo/extra/phone_logo.png',
    googleLogo = 'assets/logo/extra/google_logo.png',
    appleLogo = 'assets/logo/extra/apple_logo.png',
    emailLogo = 'assets/logo/extra/Email.png',
    profileImage = 'assets/images/Dashboard/Profile.png',
    locationImage = 'assets/images/Dashboard/LocationImage.png',
    leftImage = 'assets/images/Dashboard/Left.png',
    rightImage = 'assets/images/Dashboard/Right.png',
    greenVerifiedTick = 'assets/logo/extra/verified.png',
    accountCreatedSuccessfullyImage = 'assets/images/profile/Successmark.png',
    verificationImage = 'assets/images/Dashboard/Successmark.png';
